//! The force gate, headless: does this action need a grant, and mint one.
//!
//! The browser draws a prompt; `ds` has no dialog and must not grow one. It
//! asks the same kernel policy, and when the operator supplies the
//! confirmation on the command line it receives the same gesture-bound grant
//! token the page receives. No command in this slice SPENDS one yet: the
//! forced-run commands that will accept it are not written, so this mints and
//! reports, and nothing more. The secret itself never appears here: only the
//! kernel holds it, and
//! `pipeline.force` on ds-brain remains the authorization gate.
use ds_cli_contract::outcome::Failure;
use ds_cli_contract::spec::{
    Arg, Authority, Availability, Chapter, Command, Effect, Example, Execution, Refusal,
};
use ds_cli_contract::{Context, Inputs};
use serde_json::{Value, json};

fn local() -> Availability {
    Availability::Available
}

const REFUSALS: &[Refusal] = &[Refusal {
    code: "force_gate_input_invalid",
    when: "The action is outside the gated vocabulary, the gesture is empty, or a number does not parse",
    remedy: "Pass --action from the declared choices and --gesture as a non-empty id of this one operator gesture",
}];

const ACTION: Arg = Arg::value("action", "<action>", "The gated action.")
    .required()
    .choices(&[
        "report_export",
        "reports_only_export",
        "retry_process",
        "process_batch",
        "add_to_combined",
        "combined_and_export",
        "project_run",
        "save_overwrite",
    ]);
const FORCE: Arg = Arg::switch("force", "The gesture asks to bypass the freshness guards.");
const NO_CAPABILITY: Arg = Arg::switch(
    "no-force-capability",
    "Answer as a principal without pipeline.force.",
);
const NATIVE_REPORTS: Arg = Arg::switch(
    "native-reports",
    "Reports are generated by the installed compute, not shared compute.",
);
const TARGETS: Arg = Arg::value("targets", "<n>", "Transformers this gesture spans.").default("0");
const GESTURE: Arg = Arg::value(
    "gesture",
    "<id>",
    "One operator gesture; a grant is bound to it and to --action.",
);
const CONFIRM: Arg = Arg::value(
    "confirm",
    "<code>",
    "The operator's confirmation; mints the gesture's grant when it matches.",
);
const NOW_MS: Arg = Arg::value(
    "now-ms",
    "<ms>",
    "Epoch milliseconds for the grant's expiry; defaults to this clock.",
);

pub static COMMAND: Command = Command {
    id: "design.force-gate.check",
    path: &["design", "force-gate", "check"],
    contract: 1,
    summary: "Does this forced action need a grant, and mint one.",
    purpose: "One policy for the Transformer Status register and for Project Control, which asked this in two places with two conditions. Reports the grant requirement for an action; with --gesture and a matching --confirm it mints the gesture-bound grant token a forced headless run will present. The confirmation secret lives in ds-command-kernel, never in a client string, and this is cost friction: ds-brain still re-checks pipeline.force on the call itself.",
    chapter: Chapter::Design,
    effect: Effect::ReadOnly,
    authority: Authority::None,
    execution: Execution::Sync,
    args: &[
        ACTION,
        FORCE,
        NO_CAPABILITY,
        NATIVE_REPORTS,
        TARGETS,
        GESTURE,
        CONFIRM,
        NOW_MS,
    ],
    output: "{policy{requires_grant, reason_key, target_count?}} and, when a confirmation was offered, {grant{granted, reason_key, token?, expires_at_ms?}}.",
    examples: &[Example {
        command: "ds design force-gate check --action retry_process --force --output json",
        note: "`.data.policy.requires_grant` false means the run may proceed unconfirmed.",
        runnable: true,
    }],
    refusals: REFUSALS,
    reference: Some("docs/reference/design.md"),
    availability: local,
};

fn invalid(e: impl std::fmt::Display) -> Failure {
    Failure::invalid("force_gate_input_invalid", e.to_string())
        .remedy("Pass --action from the declared choices and --gesture as a non-empty gesture id")
}

fn ask(request: Value) -> Result<Value, Failure> {
    let reply =
        ds_command_kernel::force_gate::evaluate(&serde_json::to_vec(&request).map_err(invalid)?)
            .map_err(invalid)?;
    let parsed: Value = serde_json::from_str(&reply).map_err(invalid)?;
    Ok(parsed["result"].clone())
}

pub fn run(i: &Inputs, _c: &Context) -> Result<Value, Failure> {
    let action = i.require("action")?;
    let targets: u32 = i.require("targets")?.trim().parse().map_err(invalid)?;
    let mut out = json!({
        "action": action,
        "policy": ask(json!({
            "op": "policy",
            "action": action,
            "force": i.switch("force"),
            "capability_force": !i.switch("no-force-capability"),
            "native_report_generation": i.switch("native-reports"),
            "target_count": targets,
        }))?,
    });
    if let Some(answer) = i.value("confirm") {
        let gesture = i
            .value("gesture")
            .ok_or_else(|| invalid("a confirmation needs the --gesture it belongs to"))?;
        let now_ms: u64 = match i.value("now-ms") {
            Some(raw) => raw.trim().parse().map_err(invalid)?,
            None => std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map_err(invalid)?
                .as_millis() as u64,
        };
        out["grant"] = ask(json!({
            "op": "verify",
            "action": action,
            "gesture": gesture,
            "answer": answer,
            "now_ms": now_ms,
        }))?;
    }
    Ok(out)
}

pub fn render(data: &Value) -> String {
    let policy = &data["policy"];
    let mut out = format!(
        "  {:<18} {}\n  {:<18} {}\n",
        "requires grant",
        policy["requires_grant"],
        "why",
        policy["reason_key"].as_str().unwrap_or("")
    );
    if let Some(grant) = data["grant"].as_object() {
        out.push_str(&format!("  {:<18} {}\n", "granted", grant["granted"]));
        if let Some(token) = grant["token"].as_str() {
            out.push_str(&format!("  {:<18} {token}\n", "grant"));
            out.push_str(&format!(
                "  {:<18} {}\n",
                "expires at ms", grant["expires_at_ms"]
            ));
        }
    }
    out
}
