#!/usr/bin/env python3
"""Print the verb -> MCP tool audit table for one `ds` executable.

Usage: scripts/mcp-tool-audit.py <path-to-ds> > docs/reference/mcp-tool-audit.md

Everything is read from the executable itself: the registry through
`ds capabilities` (schema mode, so no live availability is resolved) and the
published tools through `ds mcp serve --exposure commands`. The table is a
snapshot for readers; the guarantee that every registered command is exactly
one tool is `every_registered_command_is_exactly_one_mcp_tool_or_a_named_exclusion`
in `crates/ds/tests/mcp.rs`. Deterministic, standard library only.
"""
import json
import os
import subprocess
import sys

DESKTOP_AUTHORITIES = {"desktop_pairing", "desktop_user", "project"}


def run(ds, args, stdin=None):
    env = dict(os.environ, DS_CLI_SCHEMA_ONLY="1", DS_CLI_NONINTERACTIVE="1")
    completed = subprocess.run(
        [ds, *args], input=stdin, capture_output=True, text=True, env=env, check=False
    )
    return completed.stdout


def capabilities(ds, selector=None):
    args = ["capabilities"] + ([selector] if selector else []) + ["--output", "json"]
    return json.loads(run(ds, args))["data"]


def published_tools(ds):
    requests = "\n".join(
        json.dumps(request)
        for request in (
            {"jsonrpc": "2.0", "id": 1, "method": "tools/list"},
            {"jsonrpc": "2.0", "id": 2, "method": "shutdown"},
        )
    )
    output = run(ds, ["mcp", "serve", "--exposure", "commands"], stdin=requests + "\n")
    for line in output.splitlines():
        message = json.loads(line)
        if message.get("id") == 1:
            return {tool["title"]: tool for tool in message["result"]["tools"]}
    raise SystemExit("`ds mcp serve` answered no tools/list")


def confirmation(command):
    if not command.get("confirmation_required"):
        return "—"
    trigger = command.get("confirmation_trigger")
    if trigger:
        return f"when `{trigger.lstrip('-')}`"
    preview = command.get("preview_switch")
    if preview:
        return f"unless `{preview.lstrip('-')}`"
    return "required"


def router(chapter):
    return "ds_" + chapter.replace("-", "_") if chapter != "catalog" else "—"


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    ds = sys.argv[1]
    version = json.loads(run(ds, ["version", "--output", "json"]))["data"]
    tools = published_tools(ds)
    rows = []
    for domain in capabilities(ds)["domains"]:
        for summary in capabilities(ds, domain["id"])["commands"]:
            command = capabilities(ds, summary["id"])["command"]
            rows.append((domain["id"], command))

    counts = {"tool": 0, "excluded": 0}
    lines = [
        "# `ds` verb → MCP tool audit",
        "",
        "Generated by `scripts/mcp-tool-audit.py` from `ds` source "
        f"`{version['source_sha']}`{' (dirty)' if version.get('dirty') else ''}. "
        "A snapshot: a verb registered later appears as a tool with no edit, and "
        "`crates/ds/tests/mcp.rs` holds that for the live registry. See "
        "[`mcp.md`](mcp.md) for the projection rules each column comes from.",
        "",
        "Columns: **Typed tool** is the leaf under `--exposure commands` and in any "
        "profile that includes it; **Router** is the chapter tool under the default "
        "`--exposure chapters`; **Hints** are the annotations read-only / "
        "destructive / idempotent; **confirm** is when `confirm: true` (`--yes`) is "
        "required; **Desktop** marks the bounded paired-desktop gate.",
        "",
        "| Command | Typed tool | Router | Effect | Hints R/D/I | confirm | Desktop | Status |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for domain, command in rows:
        command_id = command["id"]
        tool = tools.get(command_id)
        if tool is None:
            counts["excluded"] += 1
            status = (
                "excluded: the `mcp` domain"
                if domain == "mcp"
                else "excluded: `NEVER_TOOLS`"
            )
            name, chapter_router, hints = "—", "—", "—"
        else:
            counts["tool"] += 1
            annotations = tool["annotations"]
            hints = "/".join(
                "y" if annotations[key] else "n"
                for key in ("readOnlyHint", "destructiveHint", "idempotentHint")
            )
            name = f"`{tool['name']}`"
            chapter_router = f"`{router(command['chapter'])}`"
            status = "tool, job" if command.get("execution") == "job" else "tool"
        desktop = "yes" if command["authority"] in DESKTOP_AUTHORITIES else "—"
        lines.append(
            f"| `{command_id}` | {name} | {chapter_router} | {command['effect']} "
            f"| {hints} | {confirmation(command)} | {desktop} | {status} |"
        )
    lines[3:3] = [
        "",
        f"{len(rows)} registered commands: {counts['tool']} typed tools, "
        f"{counts['excluded']} excluded by name, plus the `ds_catalog` and "
        "`ds_diagnostics` bootstrap tools.",
    ]
    print("\n".join(lines))


if __name__ == "__main__":
    main()
