@{
    # PLS-CADD 16.81 dialog catalogue — every modal the drivers have met, when it
    # fires, how it is recognised (title / text / control ids), and the decision.
    # A dialog that matches nothing here is UNKNOWN: the watcher dumps its full
    # control tree to the journal and returns 'unknown' — never a silent wait.
    # Buttons are addressed by control id AND must be visible+enabled; the same id
    # exists on hidden pages of tabbed dialogs (report options), which is how a
    # click can silently do nothing.
    # NEVER post 40337 (resource 126 'Wires > AutoSag', the Lite menu): on the full PLS-CADD
    # frame it is logged 'unknown menu [40337]' and PLS 16.81 crashes ~13 s later (access
    # violation 0xc0000005 at pls_cadd64.exe+0x19f5123; DESKTOP-T24AHBE 2026-09-24, Nyamagabe
    # v18). AutoSag is the Section Table route: entry section_table below.
    Version = '2026-09-24'
    Entries = @(
        @{ Name = 'progress';          When = 'during any report / analysis'; Title = '^(Checking Structures|Generating Structure Loads|Computing|Calculating|Please Wait|Sagging|Analyzing|Processing).*'; Text = ''; Action = 'wait'; ControlId = 2; Note = 'progress box with Cancel id 2 and a status line (id 535); never click; poll until it closes' }
        @{ Name = 'about';             When = 'startup';            Title = '^About PLS-CADD$';                          Text = '';                                   Action = 'click'; ControlId = 1;  Note = 'licensed options box; OK id 1' }
        @{ Name = 'tip_of_the_day';    When = 'startup';            Title = '^Tip of the Day$';                          Text = '';                                   Action = 'click'; ControlId = 1;  Note = 'Close id 1; Next Tip 1002; Show Tips 1001' }
        @{ Name = 'project_moved';     When = 'open of a copied project'; Title = '^Warning$';                           Text = 'has been moved from the directory';  Action = 'click_any_ok'; ControlId = 0; Note = 'single OK button with a non-standard id; structures still resolve through the .str absolute paths' }
        @{ Name = 'criteria_problem';  When = 'any loads/usage report'; Title = 'Criteria Problem$';                     Text = "doesn't exist|Continue displaying warning messages"; Action = 'click'; ControlId = 7; Note = 'No = redirect the rest to the Error Log window (modeless, ignore it)' }
        @{ Name = 'report_options';    When = 'after a Lines > Reports command'; Title = ' Report$';                     Text = '';                                   Action = 'options'; ControlId = 1; Note = 'tabbed: press only the VISIBLE+ENABLED OK; Survey Point Clearances: feature-code include list (2938) is stored in the project and may be stale; graphics checkbox 2855' }
        @{ Name = 'section_usage_selection'; When = 'after 40015 Section Usage'; Title = '^Section Usage$'; Text = 'Report usage on sections that include any of the selected structures'; Action = 'click'; ControlId = 1; Note = 'characterized 2026-09-23 on the approved Gisagara22 control (411 structures): selection summary id 1007 read "Structures: 1 - 411 | Circuits: All" = the default full selection; OK id 1 runs the report, Cancel id 2 aborts it. The watcher does not capture id 1007, so the caller must prove section coverage from the saved report' }
        @{ Name = 'sag_tension_span_range'; When = 'after 40403 Section Sag-Tension'; Title = '^Span Range for Section Sag-Tension$'; Text = ''; Action = 'options'; ControlId = 1; Note = 'DECEPTIVE: tabbed (Structures and Circuits | Section Sag-Tension). Report Type radios 3417 separate report per section / 3418 single report row per span; Sag-Tension Type radios 3419 Ruling Span / 3420 Finite Element — the dialog says this choice is SAVED IN THE CRI FILE, so never set 3419/3420 (it silently edits project criteria); accept the stored state with the visible &OK id 1 only (hidden-tab OK id 1 exists). Characterized 2026-09-23 on the Gisagara22 control: 3417=1, 3419=1 (RS), selection id 1007 "Structures: 1 - 411 | Circuits: All"' }
        @{ Name = 'staking_table_grid'; When = 'after 40412 Staking Table'; Title = '^Staking Table$'; Text = ''; Action = 'flow'; ControlId = 2; Note = 'DECEPTIVE: 40412 is not a text report. It opens a MODAL editable grid (grid control id 131, 76 children; hidden cell editors carry only the current row, e.g. 411 / 28469.469 / FILL IN MUYAGA(100KVA)). OK id 1 may commit grid edits to the model; Cancel id 2 leaves it untouched and is the only safe exit for a read-only run. Its rows are not capturable as text through these drivers: take staking from the DON/ds side or an approved workbook. Characterized 2026-09-23 on the Gisagara22 control' }
        @{ Name = 'clearance_voltage_interpolation'; When = 'during 40016 Survey Point Clearances (after its options)'; Title = '^Warning$'; Text = 'for which there are no required clearances in the feature code table'; Action = 'click'; ControlId = 2; Note = 'ENGINEERING-RELEVANT, record it: "<n> sections have voltages (<kV>) for which there are no required clearances in the feature code table. Program will interpolate required clearances based on the voltages that are defined in the feature code table (<kV list>)." Only OK id 2. Gisagara22 control 2026-09-23: 252 sections at 30 kV, FEA defines only 0 kV, so every clearance requirement is the 0 kV column. The watcher text is cut at 160 chars; read id 65535 in full for evidence. Incoming Rev A2 2026-09-24: ''496 sections have voltages (30 ) ... defined in the feature code table (0 ).'' It came up AFTER the watcher had returned ready, and the posted BM_CLICK on OK did not close it (dialog not active); WM_COMMAND(2, BN_CLICKED) to the dialog did (pls-report-any now runs the watcher while the frame is busy; a watcher escalation to WM_COMMAND is written but not yet proven by a failed click)' }
        @{ Name = 'pp_paging_unable_to_cut'; When = 'opening a multi-alignment project (after Restore Yes or .xyz open)'; Title = '^Warning$'; Text = 'Unable to cut pages'; Action = 'click_any_ok'; ControlId = 0; Note = 'HARMLESS, visual only (owner 2026-09-23): plan & profile sheet paging cannot cut pages because the multiple-alignment gap (Terrain/Alignment/Multiple Alignment Options, 1) is smaller than the station major grid spacing (76). Single OK id 2. Followed by the two Problem boxes below. Characterized on the Nyamagabe v2 DS export' }
        @{ Name = 'pp_paging_no_progress'; When = 'right after pp_paging_unable_to_cut'; Title = '^Problem$'; Text = 'No progress in find_next_page_start_station|No progress in place_sheets loop'; Action = 'click_any_ok'; ControlId = 0; Note = 'HARMLESS, visual only: sheet paging aborted; engineering data untouched. Two consecutive boxes, each a single OK' }
        @{ Name = 'check_section_no_criteria'; When = 'during 40015 Section Usage'; Title = '^check_section$'; Text = 'No criteria defined'; Action = 'click'; ControlId = 7; Note = 'ENGINEERING-RELEVANT: some sections carry no stringing criteria. No id 7 = redirect further occurrences to the Error Log (modeless); Yes id 6 would repeat per section. Record which sections from the Error Log / report. Characterized 2026-09-23 on the Nyamagabe v2 DS export' }
        @{ Name = 'table_clipboard_paste'; When = 'Section Table Copy && Fill Column (38079)'; Title = '^Ttable::clipboard_paste$'; Text = 'No clipboard data available'; Action = 'stop'; ControlId = 2; Note = 'the fill did NOT happen (another program read the clipboard between PLS copy and paste); pls-section-table-autosag dismisses it (OK 2) and redoes the fill; anywhere else it stops the run. Met 2026-09-25 on the v19 cap6 proof' }
        @{ Name = 'multiple_alignment_options'; When = 'after 40576 Terrain > Alignment > Multiple Alignment Options'; Title = '^Multiple Alignment Options$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'check 2815 multiple-alignment drawing routines, 2816 new P&P sheet per alignment, edit 2817 station gap between alignments (m), 2831 split/join; OK 1, Cancel 2; driven by pls-sheet-paging.ps1' }
        @{ Name = 'printing_progress'; When = 'while sheets print or save as PDF (57607 / 35987)'; Title = '^PLS-CADD$'; Text = '^Printing \| Document :'; Action = 'wait'; ControlId = 2; Note = 'PLS own print progress box (Document / Page n / Printer / Port, Cancel id 2); never click; closes when the last sheet is written' }
        @{ Name = 'insufficient_strength_criteria'; When = 'during 40014 Structure Usage / open'; Title = '^PLS-CADD$'; Text = 'Insufficient criteria to verify structure strength of '; Action = 'click'; ControlId = 7; Note = 'ENGINEERING-RELEVANT: a structure file has no strength criteria, so its usage is not checked. No id 7, as pls-report-profile / pls-backup-restore-profile answer it; name the file in the delivery notes. Met 2026-09-25 on incoming Nyamagabe Rev A (...\Desktop\opt)' }
        @{ Name = 'feature_codes_to_include'; When = 'inside report_options 40016'; Title = '^Feature codes to include$'; Text = '';                                Action = 'click'; ControlId = 3;  Note = 'Select All id 3, then OK id 1' }
        @{ Name = 'structure_range';   When = '40402 Structure Loads';  Title = '^Structure Loads Report$';               Text = 'Select the desired structure range';  Action = 'options'; ControlId = 1; Note = 'edits 2178 (start) 2179 (end) — WM_SETTEXT does not take, type with EM_SETSEL+WM_CHAR; checkboxes 2802 LCA 2803 detailed 2804 markers' }
        @{ Name = 'rtf_or_text';       When = 'Save As of a report with a bitmap'; Title = '^PLS-CADD$';                   Text = 'Convert to rtf';                     Action = 'click'; ControlId = 7;  Note = 'No keeps the text file' }
        @{ Name = 'save_changes';      When = 'exit / close project';   Title = '^PLS-CADD$';                             Text = 'Save changes to';                    Action = 'click'; ControlId = 7;  Note = 'No unless the run intends to save; Yes id 6' }
        @{ Name = 'available_structure_list'; When = 'after command 40027';    Title = '^Available Structure List$';   Text = '';                                   Action = 'flow';  ControlId = 2;  Note = 'grid dialog: cells readable only by PrintWindow (the hidden editors id=1405xxxxx carry the CURRENT row only); Cancel id 2 leaves the .str untouched; Set column shows the file value + 1' }
        @{ Name = 'last_chance_exit';  When = 'exit (57665) while a dialog is still open'; Title = '^Last chance to avoid exit without save$'; Text = 'currently open and will be closed'; Action = 'click'; ControlId = 2; Note = 'OK id 2 — but it re-raises until the named dialog is really gone: close that dialog first (pls-close-window.ps1 -ExpectedExactTitle), then OK, then save_changes' }
        @{ Name = 'save_as';           When = 'after command 33356';    Title = '^Save As$';                              Text = '';                                   Action = 'flow';  ControlId = 1;  Note = 'filename edit id 1001 (the one whose text is a file name, not the Address bar), Save id 1; default name report<n>.rtf when the document holds graphics' }
        @{ Name = 'load_fea';          When = 'after command 32805';    Title = '^Load feature code file$';                Text = '';                                   Action = 'flow';  ControlId = 1;  Note = 'filename combo edit id 1148 (first, text *.fea), Open id 1' }
        @{ Name = 'goto';              When = 'after command 40570';    Title = '^Goto$';                                  Text = 'Select the structure to zoom';       Action = 'flow';  ControlId = 1;  Note = 'structure edit 4326, OK 1; zooms the ACTIVE view' }
        @{ Name = 'error_log';         When = 'after criteria_problem -> No'; Title = '^Error Log$';                      Text = '';                                   Action = 'ignore'; ControlId = 0; Note = 'modeless; owned by the frame but never blocks' }
        @{ Name = 'repair_wizard';     When = 'open of a project with missing references'; Title = 'Repair';               Text = '';                                   Action = 'stop';  ControlId = 0;  Note = 'a path ending \0 means a data line is being read as a file name — stop, see pls-repair-continue.ps1' }
        @{ Name = 'opposite_direction'; When = 'report on a project with reversed sections'; Title = '';                  Text = 'opposite direction';                 Action = 'click'; ControlId = 7;  Note = 'from pls-report-profile.psd1' }
        @{ Name = 'backup_done'; When = 'end of 33347 File > Backup'; Title = '^Backup$'; Text = 'files backed up'; Action = 'click'; ControlId = 2; Note = 'completion box; its OK is id 2 (not 1); body ''41 files backed up from 1 project''. 2026-09-24 (Nyamagabe v18, 44 files): it came up as the .bak became stable, after Invoke-PlsBackup had returned, and closed itself ~30 s later (PLS-CADD.log FILESTUF.CPP:1980 ''[OK]: 44 files backed up from 1 project'' with no click sent); a caller must let it go before the next command; interim/pls-backup-open-interim.ps1 waits for it and presses OK id 2 by WM_COMMAND (cap5: arrived 0.2 s after return)' }
        @{ Name = 'section_table'; When = 'after 40606 Sections > Table'; Title = '^Section Table$'; Text = ''; Action = 'flow'; ControlId = 2; Note = 'THE AutoSag ROUTE (proven 2026-09-24, Nyamagabe v18, 1126 sections). Full-screen dialog; grid = child id 131 titled ''Section Table758_131'' (AfxWnd140s-type custom grid; cells readable only by PrintWindow; hidden in-place editors carry the current row). Columns: Sec #, Start/End Str # Set #, Ruling Span, Insul. Clipped, Sec Notes, Cable File, Voltage, Bundle, Wires Per Phase, Sag Condition, Sag Temp, Sag Horiz. Ten., Display Weather Case, Display Condition, Disp. Wind From, Disp. Phase, Disp. Color, Command To Apply. Command To Apply in-place combo id 129648288, 19 items: '''', Clip, Unclip, Delete, Modify, AutoSag(5), Reverse Stringing, Auto RS, Manual RS, Adjust Sag Temp., Find Graph Sag Fit Points..., Graph Sag Fit to Points..., Create Points Along Wires..., Delete Concentrated Loads, Clear length adjust, Merge length adjust, Set Surveyed Temp, Find Surveyed Temp, Pretension. The command runs on OK id 1 (column tooltip: ''Operation to perform on section after pressing Ok to leave this dialog box.''); Apply id 3; Cancel id 2 discards every edit. Sequence: click row 1 Command cell with pls-click-at -MoveCursor (the grid reads GetCursorPos while it holds capture: without parking the cursor a posted click extends the selection to wherever the real cursor sits), pls-combo -Select AutoSag, click a read-only Sec # cell to end the edit (posted Enter/Escape do not), right-click row 1 Command cell -> context menu (#32768) ''Copy && Fill Column'' id 38079 (fills all rows; verify with ''&Goto Last Row With Data'' id 38061 + PrintWindow), OK via WM_COMMAND(1). Other menu ids: Cut 33400, Copy 33401, Paste 33402, Fill 33407, Pattern Fill Down 33406, Append 33467, Clear 33408, Find 33474, Remove Row 33404, Insert Row 33405, Copy with Headings 33489, Table Report 33409, Database Export 33445, XML Export 33488. No dialog followed OK; sec 1 horizontal tension 1838.4 -> 1448.5 N and the Command column is empty on reopen. Driver: pls-section-table-autosag.ps1 (+ pls-context-menu.ps1), proven on cap5 2026-09-24' }
        @{ Name = 'section_table_command_tooltip'; When = 'hovering the Section Table Command To Apply column'; Title = '^Operation to perform on section after pressing Ok'; Text = ''; Action = 'ignore'; ControlId = 0; Note = 'tooltip window owned by the Section Table, not a prompt' }
        @{ Name = 'backup_file'; When = 'after command 33347'; Title = '^Backup$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'modern Save picker: filename edit id 1001 whose text ends .bak (the Address bar is also id 1001); Save id 1; give a full path' }
        @{ Name = 'backup_options'; When = 'after the backup file picker'; Title = '^Backup Options$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'checkboxes: raster 2427, vector 2425, parts 2428, files referenced in parts 2430, tin 2426, reference manager 38366, COMPRESS 1689 (uncheck so ds-io can parse), transmit to PLS 1685 (never); OK 1' }
        @{ Name = 'save_before_backup'; When = 'after 33347 when the project has unsaved changes'; Title = '^PLS-CADD$'; Text = 'before backing up'; Action = 'click'; ControlId = 7; Note = 'No = back up the on-disk files; Yes id 6 only when the run intends to save' }
        @{ Name = 'restore_file'; When = 'after command 33348'; Title = '^Restore Backup$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'LEGACY picker: filename edit id 1148 (first of three), Open id 1' }
        @{ Name = 'restore_mapping'; When = 'after the restore file picker'; Title = '^Directory Mapping For Restore$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'grid Current directory | New Directory | Pick Directory (read by PrintWindow); Quick Restore 1741 (flattens to one folder), Show File Names 1528, Change Common Directory Path 1666; OK 1 starts the restore' }
        @{ Name = 'restore_common_path'; When = 'after 1666'; Title = '^Change Common Directory Path$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'edit 1729 is pre-filled with the DEEPEST common dir (...\struct): set it to the workspace root so every row rebinds; New Directory Path button 1708 opens select_directory and then carries the chosen path as its caption; OK 1' }
        @{ Name = 'select_directory'; When = 'after 1708'; Title = '^Select directory \(Currently'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'modern folder picker: Folder name 1152 does NOT navigate; use pls-pick-folder.ps1 (Ctrl+L, path, Enter, verify Address toolbar id 1001, Select Folder id 1); the folder must already exist' }
        @{ Name = 'restore_done'; When = 'end of a restore'; Title = '^Restore Backup of '; Text = 'files restored'; Action = 'flow'; ControlId = 6; Note = '''41 files restored, 0 files skipped  Would you like to open project ...xyz?'' Yes 6 opens the restored project; No 7 leaves PLS bare' }
        @{ Name = 'sheet_print_setup'; When = 'after 57607 in a Sheets View'; Title = '^Sheet Print Setup$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'radios 2430 unscaled / 2431 scaled / 2432 screen dump, 2433 one job per page; OK 1 -> the standard Print dialog' }
        @{ Name = 'print'; When = 'after sheet_print_setup'; Title = '^Print$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'printer combo 1139 (CB_SETCURSEL + CBN_SELCHANGE), All 1056 / Pages 1058, from 1152, to 1153 (pre-filled with the sheet count = a free page counter), copies 1154; OK 1' }
        @{ Name = 'save_print_output'; When = 'after Print with Microsoft Print to PDF'; Title = '^Save Print Output As$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'filename edit = the id-1001 edit with EMPTY text (not the Address bar); Save 1; the frame stays disabled until the spooler finishes' }
        @{ Name = 'read_annotation_don'; When = 'after 40521'; Title = '^Read Annotation from DON file$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'picker: edit 1148, Open 1' }
        @{ Name = 'merge_annotation_scope'; When = 'after the DON is picked'; Title = '^Merge in Annotation from Another Project$'; Text = 'only global annotations'; Action = 'click'; ControlId = 1; Note = 'OK 1 merges the global annotation block only (line-specific blocks are skipped)' }
        @{ Name = 'attachment_manager'; When = 'after 35904'; Title = '^Attachment Manager$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'MODELESS (frame stays enabled): list id 1532 (owner-drawn rows ~21 px, select with pls-click-at), Attach 1535, Detach 1536, Show 1537, Hide 1538, Options 1539, Report 1691, Select combo 1817 (All/None/Raster/Vector); OK 1' }
        @{ Name = 'open_attachment'; When = 'after Attach'; Title = '^Open Attachment$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'picker: edit 1148 (first), Open 1' }
        @{ Name = 'bitmap_options'; When = 'after a raster file is picked / Options on a raster row'; Title = '^Bitmap Options$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'Attach to combo 1546 (Plan view, Prof view, Sheet view, Background plan/3d/prof, Plan view vertical plane, Inset View); sheet range combo 1685 (Single/All/Title/Note/Drawing/Appendix Sheets); X 1547 Y 1548 Z 1549 W 1550 H 1551 (upper-left corner; cm and Y FROM THE TOP in Sheet view); opaque 1529 / transparent 1530 / translucent 1531 + opacity 1560; line-work 1610; OK 1' }
        @{ Name = 'shift_scale_dxf'; When = 'after a DXF is picked for a sheet view'; Title = '^Shift/Scale DXF Drawing$'; Text = 'coincide with page size'; Action = 'click'; ControlId = 7; Note = 'No when the border is drawn 1:1 at the page size in page units; Yes rescales the drawing extents onto the page (border made for another size)' }
        @{ Name = 'dxf_overlay_options'; When = 'after shift_scale_dxf / Options on a DXF row'; Title = '^DXF Overlay Options$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'Attach to combo 1534 (''Sheets view: DXF coordinates are x,y,z in cm''), sheet range 1685, text-size 1542/1548, TrueType text style 1547, DXF colors 1543, line weight 1546, extra scale/rotation 1544, paper-space filter 1545, extents 1733; layer grid (PrintWindow) with per-layer entity counts; OK 1. Supported entities: TEXT MTEXT ATTRIB ATTDEF CIRCLE ARC ELLIPSE LINE POLYLINE LWPOLYLINE SOLID TRACE 3DFACE POINT BLOCK; SPLINE/LEADER approximated; HATCH and IMAGE are NOT drawn' }
        @{ Name = 'save_dxf_file'; When = 'after 218 File > Export > DXF'; Title = '^Save DXF file$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'modern picker: edit 1001 with a .dxf name; Save 1' }
        @{ Name = 'export_dxf'; When = 'after the DXF name'; Title = '^Export DXF$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'detail combo 1736 (Low/Medium/Standard/High), 2D 35913 / 3D 35914, quote-delimit script names 1686; OK 1' }
        @{ Name = 'save_all_pages'; When = 'DXF export from a Sheets View'; Title = '^Save All Pages$'; Text = 'all pages to the same DXF'; Action = 'flow'; ControlId = 7; Note = 'Yes 6 = every sheet in ONE dxf; No 7 = one file per sheet (SHEET1.DXF..., plus PAGES, PLOT.SCR, XREF.SCR beside the chosen name) after sheets_named_note; Cancel 2' }
        @{ Name = 'sheets_named_note'; When = 'after Save All Pages -> No'; Title = '^Note$'; Text = 'SHEET1.DXF, SHEET2.DXF'; Action = 'click'; ControlId = 1; Note = 'OK 1 starts writing one DXF per sheet (84 sheets = 41 MB, about a minute); Cancel 2 aborts' }
        @{ Name = 'save_pps'; When = 'after 32830'; Title = '^Save Page Settings file$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'modern picker: edit 1001 with a .pps name; Save 1' }
        @{ Name = 'line_edit'; When = 'after 40008 Lines > Edit'; Title = '^Line$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'Project Notes edit (%R rows) + Project Lines grid (line name = %L, cost from the .str catalog); OK 1' }
        @{ Name = 'pp_config'; When = 'after 40050/40051/40052/40054/32829/32892/40506/38175'; Title = '^(Scales|Page Size|Page Layout|Pages and Station Range|P&P Sheet (Profile|Plan) View Labels|Text Position, Orientation and Background|Layers, Colors, Pen Styles and Pen Thicknesses)$'; Text = ''; Action = 'flow'; ControlId = 1; Note = 'sheet configuration dialogs, driven by pls-dialog-set.ps1; control ids in the ds-pls-cadd-plan-profile-sheets skill; a dialog first appears as a 1x1 window with no children - wait for a drawn rect and children before reading it' }
        @{ Name = 'undefined_feature_codes'; When = 'report on XYZ with codes absent from the FEA'; Title = '';           Text = 'undefined feature code';             Action = 'click'; ControlId = 7;  Note = 'from pls-report-profile.psd1; the fix is the FEA, not the click' }
    )
}
